django20140317/twitter_project/analytics/urls.py
from django.conf.urls import url, patterns


urlpatterns = patterns('analytics.views',
    url(r'^$', 'home', name='home'),
)

django20140317/twitter_project/twitter/urls.py
from django.conf.urls import url, patterns


urlpatterns = patterns('twitter.views',
    url(r'^$', 'home', name='home'),
    url(r'login/$', 'log_in', name='login'),
    url(r'logout/$', 'log_out', name='logout'),
    url(r'settings/$', 'settings', name='settings'),
    url(r'registration/$', 'registration', name='registration'),
)

django20140317/twitter_project/twitter_project/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
 
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^twitter/', include('twitter.urls',namespace='twitter')),
    url(r'^analytics/', include('analytics.urls',namespace='analytics')),
  
    url(r'^admin/', include(admin.site.urls)),
)

django20140317/twitter_project/analytics/models.py
from django.db import models

# Create your models here.

django20140317/twitter_project/twitter/models.py
from django.db import models
from django.contrib.auth.models import User

class Tweet(models.Model):
    text = models.TextField(max_length=140)
    published_on = models.DateTimeField()
    user = models.ForeignKey(User)

django20140317/twitter_project/twitter/forms.py
from django import forms
from django.contrib.auth.models import User
class TweetForm(forms.Form):
	text = forms.CharField(max_length=140, widget=forms.Textarea)

class LoginForm(forms.Form):
	username = forms.CharField()
	password = forms.CharField(widget=forms.PasswordInput)


class UserSettingsForm(forms.ModelForm):
	class Meta:
		model = User
		fields = ["first_name", "last_name", "email"]

django20140317/twitter_project/analytics/views.py
from django.http import HttpResponse

def home(request):
	return HttpResponse("Home page of analytics.")

django20140317/twitter_project/twitter/views.py
from django.core.urlresolvers import reverse
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.contrib.auth import authenticate, login, logout
from twitter.models import Tweet
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from twitter.decorators import no_login_please

import datetime
from twitter.forms import TweetForm, LoginForm, UserSettingsForm

@login_required
def home(request):
	if request.method == "POST":
		f = TweetForm(request.POST)
		if f.is_valid():
			t = Tweet()
			t.user = request.user
			t.text = f.cleaned_data["text"]
			t.published_on = datetime.datetime.today()
			t.save()
		else:
			tweets = Tweet.objects.order_by("-published_on")[:5]
			return render(request,'twitter/home.html', {"tweets":tweets, 
			"f": f})
	else:
		f = TweetForm()
		tweets = Tweet.objects.order_by("-published_on")[:5]
		return render(request,'twitter/home.html', {"tweets":tweets, 
			"f": f})

@no_login_please
def log_in(request):
	if request.POST:
		f = LoginForm(request.POST)
		if f.is_valid():
			username = request.POST["username"]
			password = request.POST["password"]
			user = authenticate(username=username,password=password)
			if user is not None:
				login(request,user)
				if request.GET.has_key("next"):
					redirect_path = request.GET["next"]
				else:
					redirect_path = reverse('twitter:home')
				return HttpResponseRedirect(redirect_path)
			else:
				return HttpResponseRedirect(reverse('twitter:login'))
		else:
			if request.GET.has_key("next"):
				context = {'next': request.GET["next"]}
			else:
				context = {}	
			context["f"] = f
			return render(request,'twitter/login.html', context)						
	else:
		if request.GET.has_key("next"):
			context = {'next': request.GET["next"]}
		else:
			context = {}
		f = LoginForm()
		context["f"] = f
		return render(request,'twitter/login.html', context)


def log_out(request):
	if request.user.is_authenticated():
		logout(request)	
	
	return HttpResponseRedirect(reverse('twitter:login'))


def registration(request):
	if request.user.is_anonymous():
		if request.POST:
			username = request.POST["username"]
			password = request.POST["password"]
			password2 = request.POST["password2"]
			email = request.POST["email"]

			u = User.objects.filter(username=username)
			if u:
				return render(request,'twitter/registration.html',
							{"error_message":"Choose another username"})

			u = User.objects.filter(email=email)

			if u:
				return render(request,'twitter/registration.html',
							{"error_message":"Choose another email"})	

			if (password!=password2):
				return render(request,'twitter/registration.html',
							{"error_message":"Passwords do not match"})	

			u = User.objects.create_user(username=username,
				email=email,password=password)
			u.save()
			return log_in(request)			

		else:
			return render(request,'twitter/registration.html')
	else:
		return HttpResponseRedirect(reverse('twitter:home'))


@login_required
def settings(request):
	if request.method == "POST":
		f = UserSettingsForm(request.POST)
		if f.is_valid():
			request.user.first_name = f.cleaned_data["first_name"]
			request.user.last_name = f.cleaned_data["last_name"]
			request.user.email = f.cleaned_data["email"]
			request.user.save()
			return HttpResponseRedirect(reverse("twitter:home"))
		else:
			return render(request,"twitter/settings.html",{"f":f})

	else:
		f = UserSettingsForm(instance=request.user)
		return render(request,"twitter/settings.html",{"f":f})

django20140317/twitter_project/twitter/templates/twitter/application.html
<!DOCTYPE html>
<html>
{% load staticfiles %}
<head>
	<link rel="stylesheet" 
		  type="text/css" 
		  href="{% static 'twitter/css/bootstrap.css' %}" />
</head>
<body>
	<div class="container well">
		<h1>Twitter (in progress)</h1>

		{% block mainarea %}
		{% endblock %}
	</div>
</body>

</html>

django20140317/twitter_project/twitter/templates/twitter/home.html
{% extends 'twitter/application.html' %}

{% block mainarea %}

<a href="{% url 'twitter:logout' %}">Logout</a>
<form action="{% url 'twitter:home' %}" method='POST'>{% csrf_token %}
	{{ f.as_p }}
	<p><input type="submit" value="Tweet"/></p>
</form>
<hr>
{% for t in tweets %}
	<p><b>{{ t.user }}</b>: {{ t.text }}</p>
	<p><i>Published on: {{ t.published_on }} </i></p>
	<hr/>
{% endfor %}

{% endblock %}

django20140317/twitter_project/twitter/templates/twitter/login.html
{% extends 'twitter/application.html' %}

{% block mainarea %}
<a href="{% url 'twitter:registration' %}">Registration</a>

{% if next %}
<form action="{% url 'twitter:login' %}?next={{ next }}" method="POST">
{% else %}
<form action="{% url 'twitter:login' %}" method="POST">
{% endif %}

	{% csrf_token %}
	{{ f.as_p }}
	<input type="submit" value="Log in" />

</form>
{% endblock %}

django20140317/twitter_project/twitter/templates/twitter/registration.html
{% extends 'twitter/application.html' %}


{% block mainarea %}
<a href="{% url 'twitter:login' %}">Login</a><br/>
<p class="btn-danger span3">{{ error_message }}</p><br/><br/>
<form method="POST" action="{% url 'twitter:registration' %}">
	{% csrf_token %}
	Username<br/>
	<input type="text" name="username"/><br/>
	Email<br/>
	<input type="email" name="email"/><br/>
	Password<br/>
	<input type="password" name="password"/><br/>
	Confirm password<br/>
	<input type="password" name="password2"/><br/>
	<input type="submit" value="Register"/>
</form>

{% endblock%}

django20140317/twitter_project/twitter/templates/twitter/settings.html
<form action="{% url  'twitter:settings' %}" method="POST">
{% csrf_token %}
{{ f.as_p }}
<input type="submit" value="save"/>
</form>